2019-08-12 17:42:20 DEBUG Starting logging
2019-08-12 17:42:20 ERROR (clsRobot.py:88):disconnect():  Event Id : None m: 'NoneType' object has no attribute 'close'2019-08-12 17:42:20.469872
2019-08-12 17:42:21 DEBUG Starting logging
2019-08-12 17:42:21 ERROR (clsSocketServer.py:216):__exit__():  Event Id : None m: [Errno 9] Bad file descriptor2019-08-12 17:42:21.474225
2019-08-12 17:48:36 DEBUG Starting logging
2019-08-12 17:48:36 ERROR (clsSocketServer.py:147):Start():  Event Id : None m: [Errno 98] Address already in use2019-08-12 17:48:36.983601
2019-08-12 17:48:38 WARNING No serial number or name provided. Automatically selecting 0060135f
2019-08-12 17:48:38 DEBUG Starting logging
2019-08-12 17:48:38 ERROR (clsRobot.py:88):disconnect():  Event Id : None m: 'NoneType' object has no attribute 'close'2019-08-12 17:48:38.994506
2019-08-12 17:48:44 DEBUG Starting logging
2019-08-12 17:48:44 ERROR (clsSocketServer.py:147):Start():  Event Id : None m: [Errno 98] Address already in use2019-08-12 17:48:44.824516
2019-08-12 17:48:46 WARNING No serial number or name provided. Automatically selecting 0060135f
2019-08-12 17:48:46 DEBUG Starting logging
2019-08-12 17:48:46 ERROR (clsRobot.py:88):disconnect():  Event Id : None m: 'NoneType' object has no attribute 'close'2019-08-12 17:48:46.835727
2019-08-12 17:49:00 DEBUG Starting logging
2019-08-12 17:49:00 ERROR (clsSocketServer.py:147):Start():  Event Id : None m: [Errno 98] Address already in use2019-08-12 17:49:00.202190
2019-08-12 17:49:02 WARNING No serial number or name provided. Automatically selecting 0060135f
2019-08-12 17:49:02 DEBUG Starting logging
2019-08-12 17:49:02 ERROR (clsRobot.py:88):disconnect():  Event Id : None m: 'NoneType' object has no attribute 'close'2019-08-12 17:49:02.213190
2019-08-12 17:49:16 DEBUG Starting logging
2019-08-12 17:49:16 ERROR (clsSocketServer.py:147):Start():  Event Id : None m: [Errno 98] Address already in use2019-08-12 17:49:16.576749
2019-08-12 17:49:18 WARNING No serial number or name provided. Automatically selecting 0060135f
2019-08-12 17:49:18 DEBUG Starting logging
2019-08-12 17:49:18 ERROR (clsRobot.py:88):disconnect():  Event Id : None m: 'NoneType' object has no attribute 'close'2019-08-12 17:49:18.589258
2019-08-12 17:49:30 DEBUG Starting logging
2019-08-12 17:49:30 ERROR (clsSocketServer.py:147):Start():  Event Id : None m: [Errno 98] Address already in use2019-08-12 17:49:30.035626
2019-08-12 17:49:32 WARNING No serial number or name provided. Automatically selecting 0060135f
2019-08-12 17:49:32 DEBUG Starting logging
2019-08-12 17:49:32 ERROR (clsRobot.py:88):disconnect():  Event Id : None m: 'NoneType' object has no attribute 'close'2019-08-12 17:49:32.053881
2019-08-12 17:56:08 DEBUG Starting logging
2019-08-12 17:56:08 ERROR (clsSocketServer.py:217):__exit__():  Event Id : None m: [Errno 9] Bad file descriptor2019-08-12 17:56:08.829656
2019-08-12 17:56:21 DEBUG Starting logging
2019-08-12 17:56:21 ERROR (clsSocketServer.py:147):Start():  Event Id : None m: [Errno 98] Address already in use2019-08-12 17:56:21.749235
2019-08-12 17:56:23 WARNING No serial number or name provided. Automatically selecting 0060135f
2019-08-12 17:56:23 DEBUG Starting logging
2019-08-12 17:56:23 ERROR (clsRobot.py:88):disconnect():  Event Id : None m: 'NoneType' object has no attribute 'close'2019-08-12 17:56:23.761747
2019-08-12 17:56:37 DEBUG Starting logging
2019-08-12 17:56:37 ERROR (clsSocketServer.py:147):Start():  Event Id : None m: [Errno 98] Address already in use2019-08-12 17:56:37.496816
2019-08-12 17:56:39 WARNING No serial number or name provided. Automatically selecting 0060135f
2019-08-12 17:56:39 DEBUG Starting logging
2019-08-12 17:56:39 ERROR (clsRobot.py:88):disconnect():  Event Id : None m: 'NoneType' object has no attribute 'close'2019-08-12 17:56:39.505548
2019-08-12 17:59:14 DEBUG Starting logging
2019-08-12 17:59:14 ERROR (clsSocketServer.py:147):Start():  Event Id : None m: [Errno 98] Address already in use2019-08-12 17:59:14.104886
2019-08-12 18:00:53 DEBUG Starting logging
2019-08-12 18:00:53 DEBUG Starting logging
2019-08-12 18:00:53 ERROR (clsSocketServer.py:217):__exit__():  Event Id : None m: [Errno 9] Bad file descriptor2019-08-12 18:00:53.864647
2019-08-12 18:00:53 ERROR (clsSocketServer.py:217):__exit__():  Event Id : None m: [Errno 9] Bad file descriptor2019-08-12 18:00:53.866168
2019-08-12 18:12:40 DEBUG Starting logging
2019-08-12 18:12:40 ERROR (clsSocketServer.py:217):__exit__():  Event Id : None m: [Errno 9] Bad file descriptor2019-08-12 18:12:40.365959
2019-08-12 18:18:29 DEBUG Starting logging
2019-08-12 18:18:29 ERROR (clsSocketServer.py:147):Start():  Event Id : None m: [Errno 98] Address already in use2019-08-12 18:18:29.104706
2019-08-12 18:18:31 WARNING No serial number or name provided. Automatically selecting 0060135f
2019-08-12 18:18:31 DEBUG Starting logging
2019-08-12 18:18:31 ERROR (clsRobot.py:88):disconnect():  Event Id : None m: 'NoneType' object has no attribute 'close'2019-08-12 18:18:31.116104
2019-08-12 18:18:35 DEBUG Starting logging
2019-08-12 18:18:35 ERROR (clsSocketServer.py:147):Start():  Event Id : None m: [Errno 98] Address already in use2019-08-12 18:18:35.136061
2019-08-12 18:18:37 WARNING No serial number or name provided. Automatically selecting 0060135f
2019-08-12 18:18:37 DEBUG Starting logging
2019-08-12 18:18:37 ERROR (clsRobot.py:88):disconnect():  Event Id : None m: 'NoneType' object has no attribute 'close'2019-08-12 18:18:37.147110
2019-08-12 18:18:41 DEBUG Starting logging
2019-08-12 18:18:41 ERROR (clsSocketServer.py:147):Start():  Event Id : None m: [Errno 98] Address already in use2019-08-12 18:18:41.290805
2019-08-12 18:18:43 WARNING No serial number or name provided. Automatically selecting 0060135f
2019-08-12 18:18:43 DEBUG Starting logging
2019-08-12 18:18:43 ERROR (clsRobot.py:88):disconnect():  Event Id : None m: 'NoneType' object has no attribute 'close'2019-08-12 18:18:43.302802
2019-08-12 18:18:47 DEBUG Starting logging
2019-08-12 18:18:47 ERROR (clsSocketServer.py:147):Start():  Event Id : None m: [Errno 98] Address already in use2019-08-12 18:18:47.029402
2019-08-12 18:18:49 WARNING No serial number or name provided. Automatically selecting 0060135f
2019-08-12 18:18:49 DEBUG Starting logging
2019-08-12 18:18:49 ERROR (clsRobot.py:88):disconnect():  Event Id : None m: 'NoneType' object has no attribute 'close'2019-08-12 18:18:49.040348
2019-08-12 18:19:12 DEBUG Starting logging
2019-08-12 18:19:12 ERROR (clsSocketServer.py:147):Start():  Event Id : None m: [Errno 98] Address already in use2019-08-12 18:19:12.541696
2019-08-12 18:19:14 WARNING No serial number or name provided. Automatically selecting 0060135f
2019-08-12 18:19:14 DEBUG Starting logging
2019-08-12 18:19:14 ERROR (clsRobot.py:88):disconnect():  Event Id : None m: 'NoneType' object has no attribute 'close'2019-08-12 18:19:14.554147
2019-08-12 18:19:19 DEBUG Starting logging
2019-08-12 18:19:19 ERROR (clsSocketServer.py:147):Start():  Event Id : None m: [Errno 98] Address already in use2019-08-12 18:19:19.588077
2019-08-12 18:19:21 WARNING No serial number or name provided. Automatically selecting 0060135f
2019-08-12 18:19:21 DEBUG Starting logging
2019-08-12 18:19:21 ERROR (clsRobot.py:88):disconnect():  Event Id : None m: 'NoneType' object has no attribute 'close'2019-08-12 18:19:21.599166
2019-08-12 18:19:27 DEBUG Starting logging
2019-08-12 18:19:27 ERROR (clsSocketServer.py:147):Start():  Event Id : None m: [Errno 98] Address already in use2019-08-12 18:19:27.225915
2019-08-12 18:19:29 WARNING No serial number or name provided. Automatically selecting 0060135f
2019-08-12 18:19:29 DEBUG Starting logging
2019-08-12 18:19:29 ERROR (clsRobot.py:88):disconnect():  Event Id : None m: 'NoneType' object has no attribute 'close'2019-08-12 18:19:29.238363
2019-08-12 18:22:15 DEBUG Starting logging
2019-08-12 18:22:15 ERROR (clsSocketServer.py:217):__exit__():  Event Id : None m: [Errno 9] Bad file descriptor2019-08-12 18:22:15.663951
2019-08-12 18:24:30 DEBUG Starting logging
2019-08-12 18:24:30 ERROR (clsRobot.py:32):connect():  Event Id : None m: Failed to get control of Vector.

Please verify that Vector is connected to the internet, is on a flat surface, and is fully charged.


Surpassed timeout of 10s2019-08-12 18:24:30.253975
2019-08-12 18:24:30 ERROR exception calling callback for <Future at 0xb3b26690 state=finished returned BehaviorControlResponse>
Traceback (most recent call last):
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.7/asyncio/futures.py", line 362, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 733, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2019-08-12 18:24:43 DEBUG Starting logging
2019-08-12 18:24:43 ERROR (clsRobot.py:88):disconnect():  Event Id : None m: 'NoneType' object has no attribute 'close'2019-08-12 18:24:43.272108
